version: "3"

services:
  database:
    container_name: Postgre
    image: postgres:alpine3.18
    ports:
      - 808:5432
    volumes:
      - posgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<user_password>

  pgAdmin:
    depends_on:
      - database
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    ports:
      - 8081:80
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=user_pass
      - PGADMIN_DEFAULT_EMAIL=ricardopuc212@gmail.com

volumes:
  posgre:
    external: true